#!/bin/sh

PATH=/sbin:$PATH

printf "uname -r:\n" >&3 
echo `uname -a` >&3
printf "\n\n/proc/version:\n" >&3
cat /proc/version >&3
printf "\n\n" >&3

if [ -e /proc/driver/nvidia/version ]; then
  printf "/proc/driver/nvidia/version:\n" >&3 
  cat /proc/driver/nvidia/version
  printf "\n\n" >&3
fi

if (lspci --version) > /dev/null 2>&1; then
  LC_ALL=C lspci | grep 'VGA compatible controller:' >&3
  LC_ALL=C lspci -n | grep 'Class 0300:' >&3
  printf "\n" >&3
fi

#if [ -e /etc/X11/XF86Config-4 ]; then
#  cat /etc/X11/XF86Config-4 >&3
#  printf "\n" >&3
#fi

#if [ -e /var/log/XFree86.0.log ]; then
#  cat /var/log/XFree86.0.log >&3
#  printf "\n" >&3
#fi

#ls -d -l /var/log/XFree86.*.log >&3 2> /dev/null
