#!/bin/sh -e

# Patch by Juergen Kreileder <jk@blackdown.de>

if [ $# -lt 1 ]; then
    echo >&2 "basename $0: script expects -patch|-unpatch as argument"
    exit 1
fi
	  
patch_opts="-f -N --no-backup-if-mismatch -p3"
	  
echo $1
	  
case "$1" in
     -patch) patch $patch_opts -p0 < $0;;
     -unpatch) patch $patch_opts -p0 -R < $0;;
     *)
        echo >&2 "basename $0: script expects -patch|-unpatch as argument"
        exit 1;;
esac
	       
exit 0
	       
@DPATCH@
--- nv/nv.c.orig        2004-07-27 17:30:05.000000000 +0200
+++ nv/nv.c     2004-10-24 18:34:11.035105823 +0200
@@ -15,6 +15,13 @@
 #include "nv_compiler.h"
 #include "os-agp.h"
 
+#if (LINUX_VERSION_CODE > KERNEL_VERSION(2, 6, 8))
+#define __VMALLOC_RESERVE (128 << 20)
+#if (LINUX_VERSION_CODE > KERNEL_VERSION(2, 6, 9))
+#define pci_find_class(a, b) pci_get_class(a, b)
+#endif
+#endif
+
 #ifdef MODULE_ALIAS_CHARDEV_MAJOR
 MODULE_ALIAS_CHARDEV_MAJOR(NV_MAJOR_DEVICE_NUMBER);
 #endif
