#!/bin/sh -e

# Patch by Juergen Kreileder <jk@blackdown.de>

if [ $# -lt 1 ]; then
    echo >&2 "basename $0: script expects -patch|-unpatch as argument"
    exit 1
fi
	  
patch_opts="-f -N --no-backup-if-mismatch -p3"
	  
echo $1
	  
case "$1" in
     -patch) patch $patch_opts -p0 < $0;;
     -unpatch) patch $patch_opts -p0 -R < $0;;
     *)
        echo >&2 "basename $0: script expects -patch|-unpatch as argument"
        exit 1;;
esac
	       
exit 0
	       
@DPATCH@
--- /home/jk/nv.c	2004-03-25 07:24:42.000000000 +0100
+++ nv/nv.c	2004-03-25 07:44:24.000000000 +0100
@@ -47,6 +47,21 @@
 devfs_handle_t nv_devfs_handles[NV_MAX_DEVICES+1];
 #endif
 
+#if defined(KERNEL_2_6) && defined(HAVE_CLASS_SIMPLE)
+static struct pci_device_id nvidia_pci_tbl[] = {
+    {
+        .class          = (PCI_CLASS_DISPLAY_VGA << 8),
+        .class_mask     = ~0,
+        .vendor         = PCI_VENDOR_ID_NVIDIA,
+        .device         = PCI_ANY_ID,
+        .subvendor      = PCI_ANY_ID,
+        .subdevice      = PCI_ANY_ID,
+    },
+    { }
+};
+MODULE_DEVICE_TABLE (pci, nvidia_pci_tbl);
+#endif
+
 // #define NV_DBG_MEM 1
 #undef NV_DBG_MEM
 
