#!/bin/sh

RELEASE=190.53

############################################################################

DIRNAME_X86=NVIDIA-Linux-x86-${RELEASE}-pkg0
DIRNAME_X86_64=NVIDIA-Linux-x86_64-${RELEASE}-pkg2
FILENAME_X86=${DIRNAME_X86}.run
FILENAME_X86_64=${DIRNAME_X86_64}.run
BASE_URL_X86=ftp://download.nvidia.com/XFree86/Linux-x86/${RELEASE}
BASE_URL_X86_64=ftp://download.nvidia.com/XFree86/Linux-x86_64/${RELEASE}

case "$1" in
    VERSION)
        echo "$RELEASE"
        ;;
    URL_X86)
        echo "$BASE_URL_X86/$FILENAME_X86"
        ;;
    URL_X86_64)
        echo "$BASE_URL_X86_64/$FILENAME_X86_64"
        ;;
    FILENAME_X86_64)
	echo "$FILENAME_X86_64"
	;;
    FILENAME_X86)
	echo "$FILENAME_X86"
	;;
    DIRNAME_X86_64)
	echo "$DIRNAME_X86_64"
	;;
    DIRNAME_X86)
	echo "$DIRNAME_X86"
	;;
esac

exit 0
