#!/bin/sh
set -e


if [ "$1" = "configure" ]
then

	if [ -x /usr/lib/nvidia/check-for-conflicting-opengl-libraries ]
	then
		/usr/lib/nvidia/check-for-conflicting-opengl-libraries
	fi

	if [ -x /usr/lib/nvidia/check-for-mismatching-nvidia-module ]
	then
		/usr/lib/nvidia/check-for-mismatching-nvidia-module
	fi

	if [ -x /usr/lib/nvidia/create-xorg-nvidia-conf ]
	then
		/usr/lib/nvidia/create-xorg-nvidia-conf
	fi

fi


#DEBHELPER#

exit 0
